use_frameworks!

target 'VidiunClient_Example' do
  pod 'VidiunClient', :path => '../'

  target 'VidiunClient_Tests' do
    inherit! :search_paths

    pod 'VidiunClient', :path => '../'
    pod 'VidiunClient/Metadata', :path => '../'
    pod 'Quick', '~> 1.0.0'
    pod 'Nimble', '~> 7.0.3'
  end
end