use_frameworks!

target 'VidiunClient_Example' do
  pod 'VidiunOttClient', :path => '../VidiunOttClient.podspec'

  target 'VidiunClient_Tests' do
    inherit! :search_paths

    pod 'VidiunOttClient', :path => '../VidiunOttClient.podspec'
    pod 'Quick', '~> 1.0.0'
    pod 'Nimble', '~> 7.0.3'
  end
end
